tutorial/views.py
import os
import sys
from flask import render_template, flash, redirect
from flask import session, url_for, request, g
from flask import Blueprint
from flask import Response
from flask import copy_current_request_context
from flask.ext.login import login_user, logout_user, login_required
from flask.ext.security import current_user
from tutorial.forms import FileUploadForm, AddDatasetForm, \
     AddQueryToDatasetForm, MakeGpsRemapForm, AddTabdataDatasetForm, \
     ChangeTabdataDatasetCsvForm, EditTabdataDatasetForm, \
     AddCsvToDatasetForm, AddTabdataQueryForm
from tutorial.models import User, db, Dataset, Csv_fileref, \
     Query, Query_instance, Gps_remap
from tutorial.models import Tabdata_dataset, Tabdata_query, \
     Tabdata_query_instance
from marion_biblio.progressivegenerators import QueueReporter
from tutorial.geocache import get_location
import json
import logging
import gevent
tutorial_bp = Blueprint('tutorial_bp', __name__, template_folder='templates')


def authorlink_filter(s):
    return 'http://scholar.google.com/scholar?q={0}'.format(s)

tutorial_bp.add_app_template_filter(authorlink_filter, "authorlink")


@tutorial_bp.before_request
def before_request():
    g.user = current_user


@tutorial_bp.route("/logout")
def logout():
    logout_user()
    return redirect(url_for('index'))


# @oid.after_login
def after_login(resp):
    if resp.email is None or resp.email == "":
        flash('Invalid login.  Please try again.')
        return redirect(url_for('login'))
    user = User.query.filter_by(email=resp.email).first()
    if user is None:
        nickname = resp.nickname
        if nickname is None or nickname == "":
            nickname = resp.email.split("@")[0]
        user = User(nickname=nickname, email=resp.email)
        db.session.add(user)
        db.session.commit()
    remember_me = False
    if 'remember_me' in session:
        remember_me = session['remember_me']
        session.pop('remember_me', None)
    login_user(user, remember=remember_me)
    return redirect(request.args.get('next') or url_for('index'))

# @app.route("/upload")


@tutorial_bp.route("/")
@tutorial_bp.route("/index")
@login_required
def index():
    user = g.user
    return render_template('index.html',
                           title='Home',
                           user=user,
                           datasets=list(user.datasets),
                           tabdata_datasets=list(user.tabdata_datasets))

@tutorial_bp.route('/upload_file/', methods=("GET", "POST"))
@login_required
def upload_file():
    form = FileUploadForm()
    filename = None
    if form.validate_on_submit():
        current_user.add_file(form.file_1.data)
        return redirect(url_for('tutorial_bp.index'))
    else:
        filename = None
    # print("Errors: " + str(form.errors))
    return render_template('upload_file.html',
                           form=form, filename=filename)


@tutorial_bp.route('/add_dataset/', methods=('GET', 'POST'))
@login_required
def add_dataset():
    form = AddDatasetForm()
    if form.validate_on_submit():
        current_user.add_dataset(form.descriptionField.data,
                                 form.queryField.data)
        return redirect(url_for('tutorial_bp.index'))
    else:
        pass
    return render_template('add_dataset.html', form=form)


@tutorial_bp.route('/add_tabdata_dataset/', methods=('GET', 'POST'))
@login_required
def add_tabdata_dataset():
    """
    adds a tabular (CSV) dataset
    """
    form = AddTabdataDatasetForm()
    if form.validate_on_submit():
        new_set = current_user.add_tabdata_dataset(
            form.descriptionField.data, form.file_1.data)
        return redirect(
            url_for('tutorial_bp.edit_tabdata_dataset',
                    **{'tabdata_dataset_id': new_set.id}))
    else:
        flash("Error in form validation: " + repr(form.errors))
    return render_template('add_tabdata_dataset.html', form=form)


@tutorial_bp.route('/edit_tabdata_dataset/<tabdata_dataset_id>',
                   methods=('GET', 'POST'))
@login_required
def edit_tabdata_dataset(tabdata_dataset_id):
    """
    Edits an existing dataset, allowing change of description and CSV file
    """
    dataset = Tabdata_dataset.query.get(int(tabdata_dataset_id))
    upload_form = ChangeTabdataDatasetCsvForm()
    edit_form = EditTabdataDatasetForm()
    add_query_form = AddQueryToDatasetForm()
    add_query_form.query.choices = \
      [(q.id, q.name) for q in Tabdata_query.query.order_by('name')]
    if upload_form.validate_on_submit():
        dataset.add_csv(upload_form.file_1.data)
        flash("File updated")
        return redirect(url_for(
            'tutorial_bp.edit_tabdata_dataset',
            **{'tabdata_dataset_id': dataset.id}))
    else:
        if len(upload_form.errors) > 0:
            flash("Upload form error: " + repr(upload_form.errors))
    if edit_form.validate_on_submit():
        if edit_form.verifyDeleteCheckbox.data is True \
          and edit_form.delete_button.data is True:
            db.session.delete(dataset)
            db.session.commit()
            return redirect(url_for('tutorial_bp.index'))
    else:
        if len(edit_form.errors) > 0:
            flash("Edit form error: " + repr(edit_form.errors))
    if add_query_form.validate_on_submit():
        # dataset.add_query_instance(add_query_form.query.data)
        flash("Tabdata query added!")
        return redirect(
            url_for('tutorial_bp.add_tabdata_dataset_query',
                    **{'tabdata_dataset_id': dataset.id,
                        'tabdata_query_id': add_query_form.query.data}))
    else:
        if len(add_query_form.errors) > 0:
            flash("Add query form error: " + repr(add_query_form.errors))
    return render_template(
        'edit_tabdata_dataset.html',
        tabdata_dataset=dataset,
        upload_form=upload_form,
        add_query_form=add_query_form,
        edit_form=edit_form)


@tutorial_bp.route(
    '/add_tabdata_dataset_query/<tabdata_dataset_id>_add_<tabdata_query_id>',
    methods=("GET", "POST"))
@login_required
def add_tabdata_dataset_query(tabdata_dataset_id, tabdata_query_id):
    """
    """
    dataset = Tabdata_dataset.query.get(int(tabdata_dataset_id))
    query = Tabdata_query.query.get(int(tabdata_query_id))
    parameters = json.loads(query.parameters)

    form = AddTabdataQueryForm(
        parameterFields=[{'name': key, 'choices': dataset.column_choices()}
                         for key, value in parameters.items()])
    form.setParameterChoices(parameters, dataset.column_choices())

    if form.submitButton.data is True:
        instance_parameters = {}
        for i in range(len(form.parameterFields)):
            instance_parameters[form.parameterFields[i].id] \
              = form.parameterFields[i].data
        dataset.add_query_instance(tabdata_query_id,
                                   json.dumps(instance_parameters))
        return redirect(
            url_for('tutorial_bp.edit_tabdata_dataset',
                    **{'tabdata_dataset_id': dataset.id}))
    else:
        flash("Error: " + repr(form.errors))
    return render_template(
        'add_tabdata_dataset_query.html',
        tabdata_dataset=dataset,
        tabdata_query=query, form=form)


@tutorial_bp.route('/delete_tabfile/<tabfile_id>')
@login_required
def delete_tabfile(tabfile_id):
    tabfile = Csv_fileref.query.get(int(tabfile_id))
    dataset_id = tabfile.dataset.id
    # delete the actual file
    if os.path.exists(tabfile.stored_fullpath()):
        os.remove(tabfile.stored_fullpath())
    # now delete the fileref
    db.session.delete(tabfile)
    db.session.commit()
    return redirect(url_for(
        'tutorial_bp.edit_dataset',
        **{'dataset_id': dataset_id}))


@tutorial_bp.route(
    '/delete_tabdata_query_instance/<tabdata_query_instance_id>')
@login_required
def delete_tabdata_query_instance(tabdata_query_instance_id):
    query_instance = Tabdata_query_instance.query.get(
        int(tabdata_query_instance_id))
    dataset_id = query_instance.dataset.id
    db.session.delete(query_instance)
    db.session.commit()
    return redirect(url_for(
        'tutorial_bp.edit_tabdata_dataset',
        **{'tabdata_dataset_id': dataset_id}))


@tutorial_bp.route('/delete_query_instance/<query_instance_id>')
@login_required
def delete_query_instance(query_instance_id):
    query_instance = Query_instance.query.get(int(query_instance_id))
    dataset_id = query_instance.dataset.id
    if os.path.exists(query_instance.stored_fullpath()):
        os.remove(query_instance.stored_fullpath())
    db.session.delete(query_instance)
    db.session.commit()
    return redirect(url_for(
        'tutorial_bp.edit_dataset',
        **{'dataset_id': dataset_id}))


@tutorial_bp.route('/edit_dataset/<dataset_id>', methods=('GET', 'POST'))
@login_required
def edit_dataset(dataset_id):
    dataset = Dataset.query.get(int(dataset_id))
    upload_form = AddCsvToDatasetForm()
    add_query_form = AddQueryToDatasetForm()
    add_query_form.query.choices = [(q.id, q.name)
                                    for q in Query.query.order_by('name')]
    if upload_form.validate_on_submit():
        dataset.add_csv(upload_form.file_1.data)
        return redirect(url_for('tutorial_bp.edit_dataset',
                                **{'dataset_id': dataset.id}))
    if add_query_form.validate_on_submit():
        dataset.add_query_instance(add_query_form.query.data)
        return redirect(url_for('tutorial_bp.edit_dataset',
                                **{'dataset_id': dataset.id}))
    return render_template(
        'edit_dataset.html',
        dataset=dataset,
        upload_form=upload_form,
        add_query_form=add_query_form)


@tutorial_bp.route('/regenerate_h5/<dataset_id>', methods=('GET', 'POST'))
@login_required
def regenerate_h5(dataset_id):
    dataset = Dataset.query.get(int(dataset_id))
    dataset.regenerate_h5_file()

tutorial/templates/add_dataset.html
{% extends "base.html" %}

{% block content %}
{% from "_formhelpers.html" import render_field %}
<form  action="{{ url_for('tutorial_bp.add_dataset') }}" method="POST" enctype="multipart/form-data">
{{ form.csrf_token }}
    <p>The "Description" of your data set should be a fairly short word or phrase (such as "Metamaterials since 1999" or "Papers by Albert Einstein"</p>
{{ render_field(form.descriptionField, size=80) }}
    <hr>
    <p>The "query text" field should be the query used in Web of Science or other database (such as "TS=metamaterials" or "AU=*Einstein").  It is not evaluated by Marion, merely included for your reference.
{{ render_field(form.queryField, size=80) }}

<p><input type="submit" value="Add this dataset">
</form>
<hr>
<h2>Note:</h2> once you create your dataset, it will be empty; click on its link (the "Date Created") to add data!
{% endblock %}

tutorial/templates/add_tabdata_dataset.html
{% extends "base.html" %}

{% block content %}
{% from "_formhelpers.html" import render_field %}
<form  action="/add_tabdata_dataset/" method="POST" enctype="multipart/form-data">
{{ form.csrf_token }}
{{ render_field(form.descriptionField) }}
<p>
{{ form.file_1(size=80) }}

<p><input type="submit" value="Add this CSV dataset">
</form>
{% endblock %}

tutorial/templates/add_tabdata_dataset_query.html
{% extends "base.html" %}

{% block content %}
{% from "_formhelpers.html" import render_field %}
<h2>
Adding query {{tabdata_query.description}} to {{ tabdata_dataset.description }}
</h2>
<hr>
<form action="{{ url_for('tutorial_bp.add_tabdata_dataset_query', **{ 'tabdata_dataset_id' : tabdata_dataset.id, 'tabdata_query_id' : tabdata_query.id } ) }}" method="POST" enctype="multipart/form-data">
  {{ form.csrf_token }}
  {% for field in form.parameterFields %}
  {{ render_field(field) }}
  {% endfor %}
  <p>
  {{ form.submitButton }}
</form>



{% endblock %}

tutorial/templates/base.html
<!DOCTYPE html>
<html>
  <head>
    {% if title %}
    <title>{{ title }} - Marion</title>
    {% else %}
    <title>Marion</title>
    {% endif %}
    <link rel="stylesheet" type="text/css" href="{{ url_for('bower.static', filename='bootstrap/dist/css/bootstrap.min.css') }}" />
    <link rel="stylesheet" type="text/css" href="{{ url_for('bower.static', filename='bootstrap/dist/css/bootstrap-theme.min.css') }}" />
    <script type="text/javascript" src="{{ url_for('bower.static', filename='jquery/dist/jquery.min.js') }}"></script>
    <script type="text/javascript" src="{{ url_for('bower.static', filename='bootstrap/dist/js/bootstrap.min.js') }}"></script>
    <script type="text/javascript" src="{{ url_for('bower.static', filename='d3/d3.js' ) }}" charset="utf-8"></script>
    <script type="text/javascript" src="{{ url_for('bower.static', filename='colorbrewer/colorbrewer.js' ) }}" charset="utf-8"></script>
    <script type="text/javascript" src="{{ url_for('bower.static', filename='event-source-polyfill/eventsource.min.js' ) }}" charset="utf-8"></script>
    <script src="{{ url_for('bower.static', filename='nvd3/build/nv.d3.js') }}" charset="utf-8"></script>
  </head>
  <body>
    <!-- http://www.w3resource.com/twitter-bootstrap/navbar-tutorial.php -->
      <div>
	  <a class="brand"  href="#"><h1>Marion</h1></a>
      {{ g.user.nickname }}
	<nav class="navbar navbar-default">
	    <div class="nav navbar-nav" >
		<div class="container">
		    <ul class="nav nav-tabs" >
			<li><a href="{{ url_for('tutorial_bp.index') }}">Home</a></li>
			{% if g.user.is_authenticated() %}
			<li><a href="{{ url_for('tutorial_bp.logout') }}"> Logout</a></li>
			{% endif %}
		    </ul>
		</div>
	    </div>
	</nav>
    </div>
    <hr>
    {% with messages = get_flashed_messages() %}
      {% if messages %}
        <ul>
        {% for message in messages %}
            <li>{{ message }} </li>
        {% endfor %}
        </ul>
      {% endif %}
    {% endwith %}
    {% block content %}{% endblock %}
  </body>
</html>

tutorial/templates/country_query.html
{% extends "base.html" %}
{% block content %}
{% for item in query_data.items() %}

<h2>{{ item[0] }}</h2>

{% if item[1] is not mapping %}
<table class="table table-striped">
{% for val in item[1][0:10] %}
<tr>
<td>{{ val['value'] }}</td><td>{{ val['label'] }}</td>
</tr>
{% endfor %}
{% endif %}

{% if item[0] == "country_collaboration" %}
{{ item[1] }}
{% endif %}
</table>

{% endfor %}
{% endblock %}

tutorial/templates/edit_tabdata_dataset.html
{% extends "base.html" %}

{% block content %}
{% from "_formhelpers.html" import render_field %}
<h2>
    {{ tabdata_dataset.description }}
</h2>
<hr>
<h3>CSV file for this dataset:</h3>
<p/>
{{ tabdata_dataset.filename }}
<form  action="{{ url_for('tutorial_bp.edit_tabdata_dataset', **{ 'tabdata_dataset_id' : tabdata_dataset.id }) }}" method="POST" enctype="multipart/form-data">
    <div class="form-group">
	{{ upload_form.csrf_token }}
	Change CSV file :{{ upload_form.file_1 }}
	<input type="submit" value="Upload">
    </div>
</form>

<hr>
<h2>
    Queries
</h2>
<p/>
<table class="table table-striped">
    {% for query_instance in tabdata_dataset.query_instances %}
    <tr>
	<td>
	    {{ query_instance.query_def.name }}
	</td>
	<td>
	    <a class="btn btn-default" href="{{ url_for('tutorial_bp.view_tabdata_query_instance', **{ 'tabdata_query_instance_id' : query_instance.id } ) }}">View Results - text</a>
	    <a class="btn btn-default" href="{{ url_for('tutorial_bp.vis_tabdata_query_instance', **{ 'tabdata_query_instance_id' : query_instance.id } ) }}">View Results - graphs</a></td>
	<td>
	    <a class="btn btn-default" href="{{ url_for('tutorial_bp.delete_tabdata_query_instance', **{ 'tabdata_query_instance_id' : query_instance.id } ) }}">Delete</a>
	</td>
    </tr>
    {% endfor %}
</table>
<form action="{{ url_for('tutorial_bp.edit_tabdata_dataset', **{ 'tabdata_dataset_id' : tabdata_dataset.id } ) }}" method="POST" enctype="multipart/form-data">
    <div class="form-group">
	{{add_query_form.csrf_token  }}
	Add a query: {{ add_query_form.query }}
	<input type="submit" value="Add Query">
    </div>
</form>
<hr>
<form action="{{ url_for('tutorial_bp.edit_tabdata_dataset', **{ 'tabdata_dataset_id' : tabdata_dataset.id } ) }}" method="POST" enctype="multipart/form-data">
    {{ edit_form.csrf_token }}
    Delete this dataset:
    <p>
	{{ render_field( edit_form.verifyDeleteCheckbox ) }}
	{{ render_field( edit_form.delete_button ) }}
</form> 



{% endblock %}

tutorial/templates/make_gps_remap.html
{% extends "base.html" %}
<head>
</head>
    
{% block content %}
{% from "_formhelpers.html" import render_field %}
<h2>
Defining a remap for location
</h2>
<h3>
  {{ remap_loc }}
</h3>
  

<form  action="{{ url_for('tutorial_bp.make_gps_remap', **{ 'remap_loc' : remap_loc, 'last_remap' : last_remap, 'last_lookup_lat' : last_lookup_lat, 'last_lookup_lon' : last_lookup_lon }) }}" method="POST" enctype="multipart/form-data">
  {{remap_form.csrf_token }}
  Enter a location to try to remap to:
  {{ render_field(remap_form.remap_to) }}
  {{ render_field(remap_form.test_button) }}
  <p>
    {% if last_lookup_lat != None and last_lookup_lon != None %}

    
{{ last_remap }} maps to: ({{ last_lookup_lat }}, {{ last_lookup_lon }})
<p>
    <iframe width="600" height="450" frameborder="0" style="border:0"
src = "https://www.google.com/maps/embed/v1/place?q={{last_remap}}&key=AIzaSyCUYK80IoDXUbX37v6E9br6oRrOEtOlvW8&zoom=10"></iframe>
    <!-- google maps embed api doesn't seem to like center and place in the same map -->
  <p>
    If this is correct, approve by clicking this button:
    {{ render_field( remap_form.remap_button ) }}
    {% endif %}
<hr>
</form>


{% endblock %}

tutorial/templates/subject_query.html
{% extends "base.html" %}
{% block content %}
{% for item in query_data.items() %}


{% if item[0] == "journals" or item[0] == "universities" or item[0] == "authors" %}
<h2>{{ item[0] }}</h2>
<h3>By total quantity of publications</h3>
<table class="table table-striped">
{% for val in item[1][0:10] %}
<tr>
<td>{{ val['value'] }}</td><td>{{ val['label'] }}</td>
</tr>
{% endfor %}
</table>
{% endif %}

{% if item[0] == "research_fronts" %}
<h2>Research Fronts</h2>
<p>
Research fronts are groups of papers that are often cited together,
and often represent one research area that is either under active
development or has been historically significant.  What is not shown
on this report is the frequency of cocitation of the papers, just
their total citations.
</p>
{% for group in item[1] %}
<hr>
<table border="1" class="table table-striped">
    <tr>
	<th>Citations</th>
	<th>Title</th>
	<th>Authors</th>
	<th>DOI</th>
    </tr>
{% for paper in group %}
    <tr>
	<td><b>{{ paper.weight }}</b></td>
	<td>{{ paper.title }}</td>
	<td>
	    {% for author in paper.author %}
	    <a href="{{ author | authorlink }}" >{{ author }}</a>
	    {% endfor %}
	</td>
	<td><a href="http://dx.doi.org/{{paper.doi}}" >{{ paper.doi }}</a></td>
    </tr>
{% endfor %}
</table>
{% endfor %}
{% endif %}


{% if item[0] == "papers_pagerank" %}
<h2>PageRank (Paper Citations)</h2>
<p>
PageRank, developed by Google, represents the "importance" of a document or author based
on the number of people who link to them.
</p>
<p>
    <b>Warning</b>
Note that unlike research fronts PageRank only considers periodicals and authors which
are actually in the corpus, so influential papers and authors outside the corpus 
of the Web of Science query will not be
represented
</p>
<table border="1"  class="table table-striped">
    <tr>
	<th>PageRank</th>
	<th>Title</th>
	<th>Authors</th>
	<th>DOI</th>
    </tr>
{% for paper in item[1] %}
    <tr>
	<td><b>{{ '%0.5f' % paper.pagerank|float }}</b></td>
	<td>{{ paper.title }}</td>
	<td>
	    {% for author in paper.author %}
	    <a href="{{ author | authorlink }}" >{{ author }}</a>
	    {% endfor %}
	</td>
	<td><a href="http://dx.doi.org/{{paper.doi}}" >{{ paper.doi }}</a></td>
    </tr>
{% endfor %}
</table>
{% endif %}

{% if item[0] == "authors_pagerank" %}
<h2>PageRank (Author Citations)</h2>
<p>
PageRank, developed by Google, represents the "importance" of a document or author based
on the number of people who link to them.
</p>
<p>
    <b>Warning</b>
Note that unlike research fronts PageRank only considers periodicals and authors which
are actually in the corpus, so influential papers and authors outside the corpus 
of the Web of Science query will not be
represented
</p>
<table border="1" class="table table-striped">
    <tr>
	<th>PageRank</th>
	<th>Author</th>
    </tr>
{% for author in item[1] %}
    <tr>
	<td><b>{{ '%0.5f' % author.pagerank | float }}</b></td>
	<td><a href="{{ author.author | authorlink }}">{{ author.author }}</a></td>
    </tr>
{% endfor %}
</table>
{% endif %}

{% endfor %}
{% endblock %}

tutorial/templates/tabdata_hexbin_query.html
{% extends "base.html" %}
{% block content %}

<h3>Hexbin Data</h3>
{{ query_data['nodes'] }}

<h3>Locations not geolocatable</h3>
{{ query_data['not_located'] }}

{% endblock %}

tutorial/templates/tabdata_markercluster_query.html
{% extends "base.html" %}
{% block content %}

<h3>Hexbin Data</h3>
{{ query_data['nodes'] }}

<h3>Locations not geolocatable</h3>
{{ query_data['not_located'] }}

{% endblock %}

tutorial/templates/vis_country_query.html
{% extends "base.html" %}
{% block content %}
<style>

<link href="{{ url_for('bower.static', filename='nvd3/build/nv.d3.css') }}" rel="stylesheet">

</style>

<body>
    <h1>
{{ query_instance.dataset.description }}
</h1>
<h2>Subjects (count)</h2>
Main subjects published by target country; numbers indicate number of papers flagged with that subject.  Papers can have multiple subjects.
<div id='chart_subjects'></div>
<h2>Universities (count)</h2>
Top universities, by number of papers published in dataset
<div id='chart_universities'></div>
<h2>Countries (count)</h2>
Countries involved in collaborations.  For datasets centered on a country, the first entry is probably the target country and indicates the number of papers in the dataset.
<div id='chart_countries'></div>
<h3>Country Collaborations</h3>
Chord chart showing number of collaborations between countries.  Each paper is counted once; in other words, a large team in country A collaborating with a single author in country B will only have a value of 1.
<div id='chart_country_collaborations'></div>

<script src="{{ url_for('static', filename='charts.js') }}"></script>
<script>

"use strict";
/* global nv, d3, console */
/*
var data = [ { "label": "Apples", "value": 8 },
	{ "label": "Pears", "value": 6 },
	{ "label": "Oranges", "value": 3 } ];
*/


var makeSeries = function(name, color, data) {
    return [ { "key": name, "color": color, "values": data } ];
};

// var dataSeries = makeSeries( "fruit", "#d67777", data );

// var limit = 3;
var limitedData = function( d, l ) {
    return d.map( function(d2) {
	return { "key": d2.key, "color": d2.color, "values": d2.values.slice( 0, l ) };
    } );
};


d3.json("{{ url_for('retrieve_query_result', **{'id' : query_instance.id} ) }}", function(d) {
    makeExpandableBarChart( "#chart_subjects", "Subjects", d.Subjects, 800, 600 );
    makeExpandableBarChart( "#chart_universities", "Universities", d.universities, 800, 600 );
    makeExpandableBarChart( "#chart_countries", "Countries", d.countries, 800, 600 );
    makeChordChart( "#chart_country_collaborations",
    d.country_collaboration.matrix,
    d.country_collaboration.key );

});

</script>

{% endblock %}

